### ISSUE TITLE
Recipe #103 -- Annotating a Poetry Reading

### ISSUE THREAD

**Issue by glenrobson** [IIIF/trc#34]
## Links

 * Original Issue: https://github.com/IIIF/cookbook-recipes/issues/103
 * Pull Request: https://github.com/IIIF/cookbook-recipes/pull/130
 * Preview: https://preview.iiif.io/cookbook/0103-poetry/recipe/0103-poetry-reading-annotations/

## Background and Summary

This recipe covers the following use cases:

While an audio file of a poetry performance may be divided into a track for each poem, scholars may wish to use annotations to indicate aspects of the performance of a particular poem.

A researcher might want to annotate the following types of information:

 * structural information (introduction, title, stanzas)
 * points where the performer takes a breath
 * repeated phrases

Since annotations could be available at the same time the manifest is generated, or might be a separate process that references the item manifest, both scenarios are shown.

There is a third use case where manifests are unaware of annotations on them, but the systems that display the item are aware of the annotations and pull them in, using the target block in the annotation.

**Comment by azaroth42** [comment]
The recipe is not correct, as pointed out by @mejackreed on iiif-discuss.

**Comment by glenrobson** [comment]
Thanks to the work of Rob and Sara we have resolved most of the issues raised in the earlier comment. We are now working on the following comments:

https://github.com/IIIF/cookbook-recipes/pull/130#issuecomment-567139553

These may be resolved in time for the meeting but if not maybe we can discuss provisional approval if the changes are agreed they should be made.

**Comment by glenrobson** [comment]
So in the meeting we discussed the recipe and felt it wasn't ready to be approved so we are withdrawing it from this round of the TRC and are going to work on it in January. 

The specific reasons can be seen in the pull request commentary but relates to a misunderstanding (mine) around arrays for motivations and discussion on whether the recipe should only show one way of listing annotations either inline in the manifest or linked annotation list but not both.
