### ISSUE TITLE
Recipe #046: Providing Alternative Representations

### ISSUE THREAD

**Issue by glenrobson** [IIIF/trc#54]
## Links

 * Original Issue: https://github.com/IIIF/cookbook-recipes/issues/46
 * Pull Request: https://github.com/IIIF/cookbook-recipes/pull/214
 * Preview: https://preview.iiif.io/cookbook/0046-rendering/recipe/0046-rendering/

## Background and Summary

This recipe introduces the related property and focuses on making a PDF version of the digital object available. It mentions that renderings are possible on other levels. Renderings are a very useful property and this recipe will be built on with a planned 3d rendering recipe in development. Only Mirador is listed as an example as the UV doesn't work at this time although it did work with version IIIF 2 rendering.

## Voting and changes

We welcome comments on the recipe and as well as voting +1, confused face or -1 feel free to add comments to this issue. If this issue is approved then the author will take account of the comments before we merge the branch in to the master cookbook branch.

If the recipe is rejected by the TRC then we will make the changes requested and resubmit it to a future TRC meeting. If you feel that your comments are substantial enough that the recipe should be looked at again by the TRC after the changes have been made please vote -1 (thumbs down).

Changes to the recipe will only be made after the TRC voting process has concluded.

**Comment by julsraemy** [comment]
👍 but "PDF Version" instead of "PDF Download" (line 22)

**Comment by glenrobson** [comment]
Small changes requested by TRC:
* Remove ‘archival’ object from first sentence
* Change PDF download to version 
* Should TEI be seeAlso? Could use ePub to avoid confusion.

There was also a larger discussion on the difference between `seeAlso`, `rendering` and `homepage` and it was decided the differences should be explained in this recipe and therefore it would be better to withdraw this issue and re-submit it when this text is added. This may mean rendering is submitted for review at the same time as seeAlso and/or homepage.

I have closed the issue and a new issue will be created when its ready for another review. 
Add mention of HTML source page either as rendering or related. 
Mention `homepage` as a place for the home location 
Going to withdraw this issue and work on the difference between homepage, seeAlso and rendering.

**Comment by triplingual** [comment]
I'm happy that this draft of the recipe was able to shine a light on a murky corner of the spec!
