### ISSUE TITLE
Improve clarity, definition and interactions of behaviors

### ISSUE THREAD

**Issue by azaroth42** [IIIF/trc#6]
## API Issues

* https://github.com/IIIF/api/issues/1612 - Inheritance of behaviors
* https://github.com/IIIF/api/issues/1643 - Interaction between behaviors
* https://github.com/IIIF/api/issues/1632 - Auto-advance behavior
* https://github.com/IIIF/api/issues/1679 - Unordered behavior on Collection
* https://github.com/IIIF/api/issues/1680 - Paged behavior on Collection
 
## Background

In 2.x we have the [`viewingHint` property](https://iiif.io/api/presentation/2.1/#viewinghint), that carries hints as to how the publisher would like the rendering client to process the information in the manifest. There are 7 such hints defined.

In 3.x, the `behavior` ([alpha](https://iiif.io/api/presentation/3.0/#behavior) / [beta](https://preview.iiif.io/api/image-prezi-rc2/api/presentation/3.0/#behavior)) property replaces `viewingHint`, and there are now 16 (more than double) the number of hints. Several are due to the addition of time-based media (audio and video), others are just new features that have come up. 

## Issue

In trying to rationalize and describe the behaviors, several issues came up. The biggest was how to know when a behavior applied with respect to the structure of the manifest. For example, if the manifest has the `paged` behavior, then the ranges would also have the `paged` behavior. But if a collection had the `auto-advance` behavior, would that mean that every manifest and canvas in the collection also inherited it?  Secondly, it was not clear which behaviors could be used together and which were mutually exclusive.  And finally, there were some obvious situations where behaviors needed to be valid, but were not.

## Solution

We defined inheritance rules, based on the both expected interactions and practicalities of document dereferencing. It was noted that behaviors on Ranges should only be activated when the range is somehow selected, but that the selection mechanism is UI dependent, and thus implementation dependent. The behavior table was changed from being a random order, to grouped by type of behavior and which behaviors are disjoint with each other. The disjoint-ness of behaviors is explicit in each behavior's description. 

Other related solved issues:

* It was noted that auto-advance can be associated with part of a canvas in a Range. Previously this was not allowed.
* It was noted that unordered and paged are both valid for Collections, such as when the Collection represents a multi-volume work. Previously these were not allowed.

## External Factors

None known.

**Comment by cubap** [comment]
I'm not against this at all. I am anxious that we are moving further and further from "Presentation" where I (a viewer) am given data and suggestions about what to expect are given and towards a "Presentation" where the entire experience is presented and I consume. Interaction should not break `behavior`.

**Comment by azaroth42** [comment]
Clarification from TRC call: If you object strongly (:-1:) to any of the issues in the block, then you can vote :-1: If the TRC disagrees with the proposal, we can split it up into separate issues to discuss individually.

**Comment by aisaac** [comment]
Explanation for my vote: I'm +1 for adding the behaviors, calling them 'behaviors' (it was the beginning of @azaroth42 's explanation) and making sure they they each individually make sense, as per the last 3 issues.
However, I'm strongly -1 for the first two issues as imo they venture too far into what I feel would be an hypermedia specification, like SMIL. They bring a lot of complexity (look at all these new MUST/SHOULD/SHOULD NOT!) and one is not even sure they capture all issues. I feel they can be very useful for implementers, but I would really feel much more comfortable if the spec just defined a list of behaviors, and the rules for inheritance and disjointness were given as an additional implementation guide.

**Comment by azaroth42** [comment]
Rob's response to @cubap from the call: We don't mandate anything more strenuously than in 2.x - clients can still not implement these, regardless of if they're called hints or behaviors. Also, that's not the issue being voted on :) The spec doesn't say how to implement or what the user experience should be. 

To @aisaac: I agree that there is added complexity, and that we start to look like a hyper-multi-media application specification ... but that's what the AV group was chartered to do :) The behaviors were approved already, the changes from #1612 and #1643 clarify the intent of those behaviors and how they interact. We felt that it was an error, and thus a specification issue, to have directly conflicting behaviors together -- for example you cannot be both auto-advance and no-auto-advance.  Without these issues, that would be allowed.

**Comment by aisaac** [comment]
@azaroth42 yes conflicting behaviors would be allowed, but I am not sure the benefit outweighs the cost in terms of implementation hurdles for would-be IIIF implementers. 
The publishers of complex media resource have a vested interest to do stuff that works, and I'm not expecting there would be a lot of breaking cases. And if there's a side resource (not in the spec) that gently tells how the behaviors should work together, then it will probably be very easy to have them follow it. And if all this doesn't work and the IIIF space gets full of broken hypermedia, then we could still change our approach and put the full complexity of a set of MUST/SHOULD(NOT) into the core spec. IIIF is a rather flexible environment so the merging could be done at a rather short notice, hence limiting the possible damage.

**Comment by azaroth42** [comment]
Are you volunteering to write the implementation notes? :)

That said, it would require a 4.0 to change any requirements, as opposed to now with 3.0 when we have a free hand. If it's legal in 3.0 (but broken) and it becomes not legal (because it's broken) then that's a backwards incompatible change.

**Comment by aisaac** [comment]
Yes, more work, I understand ;-) Basically I would envision something quite simple: a version of the table at https://preview.iiif.io/api/1612-behaviors/api/presentation/3.0/#behavior without the contraints and the inheritance would go in the spec, and the implementation note would be the same table with only the constraints and the inheritance and one line of introduction like "Implementers in need of guidance for when to (not) use a specific behavior can use the recommendations in the following table".

And I would say that it sounds rather like a feature, when backwards incompatible changes rule out  practices that have proven to be a hindrance for the community! 
And at least we would have a solid motivation for putting the extra complexity in the eyes of readers/implementers. Personally this table makes my eyes bleed a bit. And the Presentation API v3.0 looks like it's 25% longer than v2.1.1. I'd say it's quite a bargain considering the new stuff it brings, but this is not a reason not to save on the work we require.

**Comment by azaroth42** [comment]
### Issue 6 (Improve clarity, definition and interactions of behaviors)
  +1: 16 [ahankinson awead azaroth42 dismorfo gigamorph glenrobson irv jonhartzler joshuago78 jtweed julsraemy markpatton mcwhitaker mikeapp rentonsa zimeon]
   0: 6 [hadro jwd kzhr rsinghal sredick tpendragon]
  -1: 3 [aisaac cubap mixterj]

### Result: 16 / 25 = 0.64
No super majority, issue is referred to ex officio for decision

**Comment by zimeon** [comment]
TRC ex-officio group decide to split this into the constituent issue and consider each separately. Will now close this issue
