### ISSUE TITLE
Recipe #17: Using Transcripts with A/V Content

### ISSUE THREAD

**Issue by glenrobson** [IIIF/trc#68]
## Links

 * Original Issue: https://github.com/IIIF/cookbook-recipes/issues/17
 * Pull Request: https://github.com/IIIF/cookbook-recipes/pull/238
 * Preview: https://preview.iiif.io/cookbook/0017-using-transcripts/recipe/0017-transcription-av/

## Background and Summary

This recipe introduces Transcripts for AV content. Transcripts are text versions of an AV resource and live in the 'rendering' property of a manifest. There are a number of recipes related to transcripts, captions and subtitles. Just for clarity the definitions are included below:

 * Caption are a time based transcription of an AV resource
 * Subtitles are similar to captions but are sometimes translated into other languages. 
 * A transcription file, is a text-based representation of an audio or video file without time codes.

but a fuller explanations are available in a previous recipe:

https://iiif.io/api/cookbook/recipe/0219-using-caption-file/

## Voting and changes

We welcome comments on the recipe and as well as voting +1, confused face or -1 feel free to add comments to this issue. If this issue is approved then the author will take account of the comments before we merge the branch in to the master cookbook branch.

If the recipe is rejected by the TRC then we will make the changes requested and resubmit it to a future TRC meeting. If you feel that your comments are substantial enough that the recipe should be looked at again by the TRC after the changes have been made please vote -1 (thumbs down).

Changes to the recipe will only be made after the TRC voting process has concluded.

**Comment by mcwhitaker** [comment]
@aisaac I think the problem is nomenclature. I have said a couple of times that this recipe is for caption files, not for transcripts. So if my understanding of a caption file is different than yours, we are not speaking the same language.

**Comment by azaroth42** [comment]
I don't see that a separate recipe is needed for this, when the intention is just the default `rendering` functionality of enabling a text file to be downloaded.  The recipe causes more confusion, as can be seen above, than good.

**Comment by mcwhitaker** [comment]
I think we should change the language if people are reading it differently than I am reading it. For instance:

`A transcript in a timed-text format, however, provides the ability for clients to synchronize it with its A/V resource during playback. When that syncrhonization experience is desired, it can be accomplished using annotations as discussed in [Transformation - WebVTT or OHMS XML to Annotations][0079].
`
This is saying that the synchronization is accomplished with annotations, which is what @azaroth42  says is needed.

**Comment by aisaac** [comment]
@mcwhitaker I agree there is a nomenclature issue. I am in fact quite ready to accept definitions given to me. The problem is that there are conflicting definitions in the material I see (e.g. in the recipe and in the description of the recipe above). This is why I've used so many quotes: I'm not inventing these :-/ If recipe 17 is about "captions files" that would be different from "transcripts", which I've used indeed, then I can accept it, but please can somebody change the title of the recipe, which shouts "transcripts" at everyone?

**Comment by mcwhitaker** [comment]
Recipe 17 is for transcript files. I said what I said because you quote things I said with reference to recipe #219, which is for captions.

**Comment by tomcrane** [comment]
Not sure whether this adds or reduces confusion, but here are two examples of the same format (PDF) being linked via the two different linking mechanisms discussed above, from the same publisher.

Firstly, `rendering`. Wellcome manifests for image-based material all have a `rendering` property that points to a PDF:

https://iiif.wellcomecollection.org/presentation/b30234141

Secondly, `supplementing`. Here the video transcript happens to be available as a PDF - that existed long before IIIF. But it is a transcript of the video, so is associated with the canvas in a supplementing annotation:

(second-to-last bit of) https://iiif.wellcomecollection.org/presentation/b16676841
=> links to https://iiif.wellcomecollection.org/file/b16676841_0055-0000-3704-0000-0-0000-0000-0.pdf

This PDF document does not feel to me like a rendering of the video, it is a single supplementing annotation.

**Comment by azaroth42** [comment]
@tomcrane I think it's okay as a `rendering` ... a much reduced quality rendering, but an alternative representation of the intellectual content of that video, nonetheless. The same way, in reverse, that a 3d model is an improved quality representation of a series of 2d images.

**Comment by aisaac** [comment]
@mcwhitaker oh sorry when you said "this recipe" [here](https://github.com/IIIF/trc/issues/68#issuecomment-839796970), I thought you were refering to #17!
Maybe I could remove my comment just above, then, and then you remove the following one, to clean things.

I'm curious though: if there anything in [my bigger comment](https://github.com/IIIF/trc/issues/68#issuecomment-839198502), where I've mis-quoted you? I am not sure where we have a different understanding of captions. I agree with what is in [your first clarification comment](https://github.com/IIIF/trc/issues/68#issuecomment-839127907), for example.
If I had terminology problems, then I think there were rather about what a 'transcript' could be (and I'm still struggling reconciling the different definitions in this ticket description one one hand, and recipe #17 and your clarification on the other hand.

**Comment by mcwhitaker** [comment]
@aisaac  I think we needed a conversation and that happened during the TRC call. At the TRC call I understood better what you are trying to say. This recipe and #219 will be changed to incorporate clarifications.

**Comment by glenrobson** [comment]
After discussion in the TRC this issue and #69 will be withdrawn. The proposal is to change this recipe to be more specific on the interaction of downloading the transcription to make it clear it is a rendering use case. 

We will then create an implementation note which will point the reader to which recipe to follow for which use case. We will bring this new implementation note and the various recipes that explore the different options to a future TRC.
