### ISSUE TITLE
Recipe # 219: Using Captions and Subtitles with Video Content

### ISSUE THREAD

**Issue by glenrobson** [IIIF/trc#69]
## Links

 * Original Issue: https://github.com/IIIF/cookbook-recipes/issues/237
 * Pull Request: https://github.com/IIIF/cookbook-recipes/pull/233
 * Preview: https://preview.iiif.io/cookbook/0219-using-caption-file/recipe/0219-using-caption-file/

## Background and Summary

This is a change to a previously accepted recipe as comments were received after the voting process had concluded. 

Recipe #219 used motivation `painting` for the caption file. A discussion in the A/V Community Group slack channel argued that the `painting` motivation implied that clients are required to render the captions while the standard behavior in players in general is to make caption rendering optional. 

The topic brought back the discussion of whether or not we need a `transcribing` motivation. Looking back at prior discussions, [this comment](https://github.com/IIIF/api/pull/1807#issuecomment-483641344) in a prezi 3.0 pull request explains the reasoning used to reject (at least for 3.0) the suggestion for a `transcribing` motivation.

The currently recommended way to implement caption and subtitle files remains using the `supplementing` motivation. 

To see the changes made to this recipe please see the following diff:

https://github.com/IIIF/cookbook-recipes/pull/233/files

## Voting and changes

We welcome comments on the recipe and as well as voting +1, confused face or -1 feel free to add comments to this issue. If this issue is approved then the author will take account of the comments before we merge the branch in to the master cookbook branch.

If the recipe is rejected by the TRC then we will make the changes requested and resubmit it to a future TRC meeting. If you feel that your comments are substantial enough that the recipe should be looked at again by the TRC after the changes have been made please vote -1 (thumbs down).

Changes to the recipe will only be made after the TRC voting process has concluded.

**Comment by nfreire** [comment]
Caption files in SRT format do not have a specific mime type. These files would need to have the mime type 'text/plain", which does not allow viewers to identify the supplementing resource as a caption file.
The recipe should clarify how SRT files should be used.

**Comment by glenrobson** [comment]
After discussion in the TRC this issue and #68 will be withdrawn. This recipe will focus on the interaction where the viewer is expected to make use of the file in the `supplementing` annotation by optionally showing the vtt file along with the video. Further comments are listed in the TRC Agenda. 

We will then create an implementation note which will point the reader to which recipe to follow for which use case. We will bring this new implementation note and the various recipes that explore the different options to a future TRC.
