### ISSUE TITLE
Recipe #326: Annotate specific images or layers

### ISSUE THREAD

**Issue by glenrobson** [IIIF/trc#96]
## Links

 * Original Issue: https://github.com/IIIF/cookbook-recipes/issues/326
 * Pull Request: https://github.com/IIIF/cookbook-recipes/pull/335
 * Preview: https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/

## Background and Summary

This recipe looks at annotating a specific image when a canvas is made up of multiple images. This can be useful when there is an item that you want to draw attention to which is only present in one of the images. This matches the provided use case where the skulls are only present in the x-ray version of the image. 

No viewer currently supports this type of annotation where the annotation targets a specific layer but this may be a model followed by the maps group as they are keen to look at ways of targeting specific Map images. 

## Voting and changes

We welcome comments on the recipe and as well as voting +1, confused face or -1 feel free to add comments to this issue. If this issue is approved then the author will take account of the comments before we merge the branch in to the master cookbook branch.

If the recipe is rejected by the TRC then we will make the changes requested and resubmit it to a future TRC meeting. If you feel that your comments are substantial enough that the recipe should be looked at again by the TRC after the changes have been made please vote -1 (thumbs down). A confused face is treated as abstaining. 

Changes to the recipe will only be made after the TRC voting process has concluded.

**Comment by thehabes** [comment]
[Simplest Annotation](https://iiif.io/api/cookbook/recipe/0266-full-Canvas-annotation/) this link is 404

**Comment by thehabes** [comment]
Double highlight over the target object or just the source around
` "source": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/2000,1271/0/default.jpg#xywh=810,900,260,370"`

This is to focus on the fact the target is a fragment selector on the Image.

There was a good deal of conversation around this.  No matter what you choose to do here, you should definitely double highlight it :)

**Comment by thehabes** [comment]
Consider removing `scope` from the Annotation target.

**Comment by cubap** [comment]
Since `scope` identifies that the Canvas is the place where the `target` is relevant, the `source` should be understood not as the jpg image, but as the `id` of the Item within the Choice. This might help with the pointing.

I suggest moving the selector to the `scope` so that the Image is pointed at (and can be found within the Choice by a viewer) but the `scope` of the Annotation is limited to the small region in relation to the Canvas. In this way, the `full/max` issue is avoided and the IIIF-style of the annotation is more clear (since the `xywh` is on a IIIF Entity).

```json
"target": {
    "source": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/max/0/default.jpg",
    "scope": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/canvas/p1#xywh=810,900,260,370"
}
```

**Comment by giacomomarchioro** [comment]
Selecting the image region using percentage in the fragment selector:
`https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray/full/max/0/default.jpg#xywh=pct:40,70,16,29`
**Pros**: This would solve the uncertainty caused by changing the max image size from the server side and would keep the `id` equals expect for the fragment selector as in [recipe 0021](https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0021-tagging/)
**Cons**: we are still targeting an URL of an image

**Comment by tomcrane** [comment]
Maybe there are three recipes... separating out from the question about xywh, ImageApiSelector etc.

1. Where the annotation is inline as part of the manifest JSON, as in the example. It's clearly an anno on that image within the `Choice`, it doesn't need to introduce `scope` and `source` additional vocab. Clients just looking at the members of `canvas.items` (and not any annotations that those members themselves might have) will miss this special image-specific anno, but it's the simplest construction, it's an anno on a particular image resource.
2. Where the annotation is external to the manifest, e.g., in an annotation server. It needs `scope` and `source`, and also needs `partOf` to locate the canvas, which needs `partOf` to locate the manifest, and so on. It could also be an annotation with multiple targets.
3. For scenarios where you don't mind if a client shows the annotation regardless of which item in the `Choice` is visible, but want to provide additional information for special clients that understand how to limit it, the annotation is a regular annotation targeting the canvas, but qualified by an additional `scope` property, which is the `id` of the relevant member of the Choice. And `scope` could have multiple values - (the feature is visible at 10<sup>15</sup> Hz and at 10<sup>16</sup> Hz). This is the kind of "progressive enhancement" version of this feature - but would not be suitable if you really do not want that anno to appear in **any** viewer outside of the context of its particular scope

**Comment by glenrobson** [comment]
There was discussion in the call on using an Image API selector as a way of getting round the annotation targeting a specific image URL. Would the annotation using a selector look like this:

```
{
    "id": "https://preview.iiif.io/cookbook/0326-annotating-image-layer/recipe/0326-annotating-image-layer/annotation/p0002-tag",
    "type": "Annotation",
    "motivation": "tagging",
    "body": {
        "type": "TextualBody",
        "value": "A group of skulls.",
        "language": "en",
        "format": "text/plain"
    },
    "target": {
        "type": "SpecificResource",
        "source": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray",
        "selector": {
            "type": "ImageApiSelector",
            "region": "810,900,260,370"
        }
    }
}
```

Background info:
 * [Selectors from Annotation Spec](https://www.w3.org/TR/annotation-model/#selectors)
 * [Image API selector definition](https://iiif.io/api/annex/openannotation/#iiif-image-api-selector)
 * [Recipe using Image API selector](https://iiif.io/api/cookbook/recipe/0040-image-rotation-service/) 

This has the advantage in that it is targeting the Image API URI rather than the image URL (the one containing `full/max`). If we go for this one should we move the `annotations` into the IIIF Image `service` block or is it OK to remain in the painting annotation?

This option would also be more useful for the Maps georef extension as it works without being embedded in a Manifest and knowing the painting annotation ids. If this annotation was outside of the Manifest (and I agree this is a separate recipe) then the source could be expanded like the one proposed in the [pointing canvas annotation to a Manifest](https://github.com/IIIF/cookbook-recipes/issues/306) proposal to point either to the containing canvas or manifest.

**Comment by cubap** [comment]
> "source": "https://iiif.io/api/image/3.0/example/reference/421e65be2ce95439b3ad6ef1f2ab87a9-dee-xray",
>         "selector": {
>             "type": "ImageApiSelector",
>             "region": "810,900,260,370"
>         }

The trouble with this solution is still that the source has no dimensions associated with it, so the units on the `region` selector are unknowable. Percent fixes this, but that feels like a workaround. I have settled a bit more into my opinion that a IIIF Viewer may decide to surface Annotations (remote or embedded) that are pointing directly at an Image resource or not. The sentence of this Annotation should not be "When you look at this image, pay attention to this region," but rather "When you are viewing this Canvas, one of these Choices has an interesting region." The use case supports this, indicating an intention "to annotate a painting detail that is only visible on a *specific image* of a multi-spectral *set* of images."

If the Image resource has a direct annotation, it stands alone and may be targeted as a Web Annotation or wrapped in a Canvas to be more IIIFy. If the goal of Presentation API is to contain the representations and this annotation is calling out one image in a set which is already encoded as a Choice, then changing the mode of addressing introduces conflict, even if it feels less direct.

I'm not dying on this hill, but I feel like I can see a bit further having climbed up here. 🍻

**Comment by glenrobson** [comment]
> The trouble with this solution is still that the source has no dimensions associated with it, so the units on the region selector are unknowable.

I think as the source is a IIIF Image API URI you can get the dimensions from the info.json. You know the source is a IIIF image API because it has a ImageAPISelector so wouldn't that solve the unknown dimensions issue?

**Comment by cubap** [comment]
> wouldn't that solve the unknown dimensions issue?

It would. There isn't a promise that the "natural" dimensions remain constant, but it is not a bad way to go.

**Comment by glenrobson** [comment]
Closing issue as we need to have another go at this before it comes back to the TRC
